image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip
    - venv/

stages: 
  - test
  - publish

before_script:
  - >
    pip install -r requirements.txt --trusted-host=nexus.mdcatapult.io 
    --index=https://$NEXUS_USERNAME:$NEXUS_PASSWORD@nexus.mdcatapult.io/repository/pypi-all/pypi 
    --index-url=https://$NEXUS_USERNAME:$NEXUS_PASSWORD@nexus.mdcatapult.io/repository/pypi-all/simple

lint:
  stage: test
  script:
    - pylint --rcfile=.pylintrc src

test:
  stage: test
  script:
    - python -m pytest

publish-stable:
  stage: publish
  script:
    - python setup.py sdist bdist_wheel
    - twine upload -u $NEXUS_USERNAME -p $NEXUS_PASSWORD --repository-url https://nexus.mdcatapult.io/repository/pypi-stable/ dist/*
  only:
    - master

publish-unstable:
  stage: publish
  script:
    - python setup.py egg_info -b.build-$CI_JOB_ID sdist bdist_wheel
    - twine upload -u $NEXUS_USERNAME -p $NEXUS_PASSWORD --repository-url https://nexus.mdcatapult.io/repository/pypi-unstable/ dist/*
  except:
    - master
